export { default as UiIconEdit } from './Edit.vue'
export { default as UiIconExport } from './Export.vue'
export { default as UiIconComputer } from './Computer.vue'
export { default as UiIconMark } from './Mark.vue'
export { default as UiIconArrowRight } from './ArrowRight.vue'
export { default as UiIconArrowDown } from './ArrowDown.vue'
export { default as UiIconClose } from './Close.vue'